import { boolean, integer, pgTable, serial, varchar, text, timestamp } from 'drizzle-orm/pg-core';

export const candidates = pgTable('candidates', {
  id: serial('id').primaryKey(),
  fullName: varchar('full_name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  phone: varchar('phone', { length: 20 }).notNull(),
  linkedinUrl: varchar('linkedin_url', { length: 500 }).notNull(),
  resumePath: varchar('resume_path', { length: 500 }).notNull(),
  college: varchar('college', { length: 255 }),
  graduationYear: varchar('graduation_year', { length: 10 }),
  degreeBranch: varchar('degree_branch', { length: 255 }),
  referralSource: varchar('referral_source', { length: 255 }),
  paymentStatus: varchar('payment_status', { length: 50 }).default('pending'),
  paymentId: varchar('payment_id', { length: 255 }),
  createdAt: timestamp('created_at').defaultNow(),
});

export const companies = pgTable('companies', {
  id: serial('id').primaryKey(),
  companyName: varchar('company_name', { length: 255 }).notNull(),
  websiteUrl: varchar('website_url', { length: 500 }).notNull(),
  industry: varchar('industry', { length: 100 }),
  companySize: varchar('company_size', { length: 50 }),
  companyStage: varchar('company_stage', { length: 50 }),
  rolesHiringFor: text('roles_hiring_for'),
  contactName: varchar('contact_name', { length: 255 }).notNull(),
  contactRole: varchar('contact_role', { length: 255 }),
  contactEmail: varchar('contact_email', { length: 255 }).notNull(),
  contactPhone: varchar('contact_phone', { length: 20 }),
  contactLinkedin: varchar('contact_linkedin', { length: 500 }),
  problemTitle: varchar('problem_title', { length: 500 }).notNull(),
  problemDescription: text('problem_description'),
  businessContext: text('business_context').notNull(),
  coreTask: text('core_task').notNull(),
  expectedDeliverables: text('expected_deliverables'),
  preferredStack: varchar('preferred_stack', { length: 255 }),
  techStack: varchar('tech_stack', { length: 255 }),
  toolRestrictions: varchar('tool_restrictions', { length: 500 }),
  difficultyLevel: varchar('difficulty_level', { length: 50 }),
  nominateJury: varchar('nominate_jury', { length: 20 }),
  juryName: varchar('jury_name', { length: 255 }),
  juryDesignation: varchar('jury_designation', { length: 255 }),
  customEvalCriteria: text('custom_eval_criteria'),
  strongSolutionCriteria: text('strong_solution_criteria'),
  hiringIntent: varchar('hiring_intent', { length: 100 }),
  preferredTimeline: varchar('preferred_timeline', { length: 50 }),
  approxOpenings: varchar('approx_openings', { length: 50 }),
  numberRoles: varchar('number_roles', { length: 50 }),
  skillsLookingFor: text('skills_looking_for'),
  finalRoundAttendeeName: varchar('final_round_attendee_name', { length: 255 }),
  finalRoundAttendeeRole: varchar('final_round_attendee_role', { length: 255 }),
  suggestChallenge: boolean('suggest_challenge').default(false),
  confirmations: text('confirmations'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const companyAuditionDrafts = pgTable('company_audition_drafts', {
  id: serial('id').primaryKey(),
  status: varchar('status', { length: 50 }).notNull().default('lead_captured'),
  contactName: varchar('contact_name', { length: 255 }).notNull(),
  companyName: varchar('company_name', { length: 255 }).notNull(),
  workEmail: varchar('work_email', { length: 255 }).notNull(),
  emailVerifiedAt: timestamp('email_verified_at'),
  verificationCodeHash: varchar('verification_code_hash', { length: 255 }),
  verificationExpiresAt: timestamp('verification_expires_at'),
  websiteUrl: varchar('website_url', { length: 500 }),
  companySize: varchar('company_size', { length: 50 }),
  industry: varchar('industry', { length: 100 }),
  rolesHiringFor: text('roles_hiring_for'),
  numberRoles: varchar('number_roles', { length: 50 }),
  techStack: varchar('tech_stack', { length: 255 }),
  skillsToEvaluate: text('skills_to_evaluate'),
  problemContext: text('problem_context'),
  strongSolutionCriteria: text('strong_solution_criteria'),
  suggestChallenge: boolean('suggest_challenge').default(false),
  generatedDraftJson: text('generated_draft_json'),
  editedDraftJson: text('edited_draft_json'),
  generationCount: integer('generation_count').notNull().default(0),
  lastGeneratedAt: timestamp('last_generated_at'),
  finalRoundAttendeeName: varchar('final_round_attendee_name', { length: 255 }),
  finalRoundAttendeeRole: varchar('final_round_attendee_role', { length: 255 }),
  preferredTimeline: varchar('preferred_timeline', { length: 50 }),
  contactLinkedin: varchar('contact_linkedin', { length: 500 }),
  submittedAt: timestamp('submitted_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const juryMembers = pgTable('jury_members', {
  id: serial('id').primaryKey(),
  fullName: varchar('full_name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull(),
  linkedinUrl: varchar('linkedin_url', { length: 500 }).notNull(),
  currentRole: varchar('current_role', { length: 255 }),
  company: varchar('company', { length: 255 }),
  domainExpertise: text('domain_expertise'),
  yearsExperience: varchar('years_experience', { length: 20 }),
  availability: varchar('availability', { length: 50 }),
  motivation: text('motivation'),
  createdAt: timestamp('created_at').defaultNow(),
});
