CREATE TABLE IF NOT EXISTS "company_audition_drafts" (
	"id" serial PRIMARY KEY NOT NULL,
	"status" varchar(50) DEFAULT 'lead_captured' NOT NULL,
	"contact_name" varchar(255) NOT NULL,
	"company_name" varchar(255) NOT NULL,
	"work_email" varchar(255) NOT NULL,
	"email_verified_at" timestamp,
	"verification_code_hash" varchar(255),
	"verification_expires_at" timestamp,
	"website_url" varchar(500),
	"company_size" varchar(50),
	"industry" varchar(100),
	"roles_hiring_for" text,
	"number_roles" varchar(50),
	"tech_stack" varchar(255),
	"skills_to_evaluate" text,
	"problem_context" text,
	"strong_solution_criteria" text,
	"suggest_challenge" boolean DEFAULT false,
	"generated_draft_json" text,
	"edited_draft_json" text,
	"generation_count" integer DEFAULT 0 NOT NULL,
	"last_generated_at" timestamp,
	"final_round_attendee_name" varchar(255),
	"final_round_attendee_role" varchar(255),
	"preferred_timeline" varchar(50),
	"contact_linkedin" varchar(500),
	"submitted_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
